micronaut:
  application:
    name: userSystem
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/user_system_database
      username: root
      password: root
      schema-generate: CREATE_DROP
      dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
